eUni.Client/eUni.Client/Models/TestViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EUni_Client.Models
{
    public class TestViewModel
    {
        public int TestId { get; set; }
        public string Name { get; set; }
        public int ModuleId { get; set; }
        public List<QuestionViewModel> Questions { get; set; }
        public int Grade { get; set; }
    }
}

eUni.Client/eUni.Client/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using EUni_Client.Models;
using EUni_Client.Services;

namespace EUni_Client.Controllers
{
    public class QuestionsController : Controller
    {
        // GET: Questions
        public async Task<ActionResult> Index(TestViewModel vm)
        {
            var apiService = Session.GetApiService();

            var testQuestions =  await apiService.GetAsync<TestViewModel, int>("/Test/GetAllQuestionsByTestId", "testId", vm.TestId);

            var moduleQuestions = await apiService.GetAsync<IList<QuestionViewModel>, int>("/Question/GetAllByModuleId", "moduleId", vm.ModuleId);

            var unassigned = moduleQuestions.Where(q => !testQuestions.Questions.Any(t => t.QuestionId.Equals(q.QuestionId)));

            return View(new QuestionResultsViewModel {TestId = vm.TestId, ModuleQuestions = unassigned.ToList(), TestQuestions = testQuestions.Questions});
        }

        [HttpPost]
        public async Task AddQuestion(int questionId, int testId)
        {
            var apiService = Session.GetApiService();
            var result = await apiService.PostAsyncWithReturn<string, object>("/Question/AssignQuestionToTest", new { QuestionId = questionId, TestId = testId});
        }
    }
}

eUni.Client/eUni.Client/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using EUni_Client.Models;
using EUni_Client.Services;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;

namespace EUni_Client.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        public async Task<ActionResult> Index(int moduleId)
        {
            var apiService = Session.GetApiService();
            var tests = await apiService.GetAsync<IList<TestViewModel>, int>("/Test/GetAllTestsByModule", "moduleId", moduleId);

            foreach (var test in tests)
            {
                var g = await apiService.GetAsync<int?, object>("/Test/GetGradeForStudent", new Dictionary<string, object> {{"studentId", apiService.UserId}, {"testId", test.TestId}});
                test.Grade = g.Value;
            }

            ViewBag.ModuleId = moduleId;
            return View(tests);
        }

        [HttpPost]
        public async Task<ActionResult> Create(int moduleId, string name)
        {
            var apiService = Session.GetApiService();
            var result = await apiService.PostAsyncWithReturn<string, object>("/Test/Add", new { Name = name, ModuleId = moduleId });

            return RedirectToAction("Index", "Test", new RouteValueDictionary { { "moduleId", moduleId } });
        }


        public async Task<ActionResult> TakeTest(int testId)
        {
            var apiService = Session.GetApiService();

            var studentId = (await apiService.GetAsync<dynamic, string>("/User/GetByUsername", "username", apiService.Username)).DomainUserId;
            ViewBag.StudentId = studentId;
            ViewBag.TestId = testId;
                        
            var test = await apiService.GetAsync<TestViewModel, int>("/Test/GetAllQuestionsByTestId", "testId", testId);
            int totalScore = 0;
            test.Questions.ForEach(q => q.Answers.ForEach(a =>
            {
                totalScore = a.IsCorrect ? totalScore += q.Score : totalScore += 0;
            }));
            ViewBag.TotalScore = totalScore;

            return View(test);
        }

        public async Task<RedirectToRouteResult> SubmitTest(IEnumerable<object> testData)
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task SubmitFinalGrade(int studentId, int finalScore, int testId)
        {
            var apiService = Session.GetApiService();

            var result = await apiService.PostAsyncWithReturn<string, object>("/Test/UpdateGrade", new { StudentId = studentId, TestId = testId, Grade = finalScore });
        }

        public RedirectToRouteResult Redirect(int moduleId)
        {
            return RedirectToAction("Index", "Test", new RouteValueDictionary() {{"moduleId", moduleId}});
        }
    }
}

eUni.Client/eUni.Client/Views/Test/Index.cshtml
@using EUni_Client.Services
@model IList<EUni_Client.Models.TestViewModel>

@if (Session[ServiceNames.ApiService] != null)
{
    var role = Session.GetApiService().UserRole;
    switch (role)
    {
        case UserRole.Student:
            <div>
                <h2>Student section</h2>

                @if (Model.Count > 0)
                {
                    <table class="table table-striped table-hover">
                        <tr>
                            <th>Test</th>
                            <th>Grade</th>
                        </tr>
                        @foreach (var test in Model)
                        {
                            if (test.Grade != 0)
                            {
                                <tr>
                                    <input name="testId" type="text" value="@test.TestId" hidden />
                                    <td><input type="submit" class="btn btn-link" style="color: dodgerblue" value="@test.Name" disabled /></td>
                                    <td><h5 class="">Grde: @test.Grade</h5></td>
                                </tr>
                            }

                            else
                            {
                                using (Html.BeginForm("TakeTest", "Test"))
                                {
                                    <tr>
                                        <input name="testId" type="text" value="@test.TestId" hidden />
                                        <td><input type="submit" class="btn-link" style="color: dodgerblue" value="@test.Name" /></td>
                                        <td>Ungraded</td>
                                    </tr>
                                }
                            }

                        }
                    </table>

                }
                else
                {
                    <p>No tests to show.</p>
                }
            </div>

            break;
        case UserRole.Teacher:
            <script src="~/Scripts/jquery-2.2.0.js"></script>
            <script>
                $(document).ready(function () {
                    $('#createBtn').on('click', function () {
                        $('#hiddenForm').show();
                    });
                });
            </script>

            <h2>Tests</h2>

            if (Model.Count > 0)
            {
                foreach (var test in Model)
                {
                    using (Html.BeginForm("Index", "Questions"))
                    {
                        <input name="TestId" type="text" value="@test.TestId" hidden />
                        <input name="ModuleId" type="text" value="@test.ModuleId" hidden />
                        <input type="submit" class="btn-link" style="color: dodgerblue" value="@test.Name" />
                    }
                }
            }
            else
            {
                <p>No tests to show.</p>
            }

            <button type="submit" class="btn btn-default" id="createBtn">Create Test</button>

            <div id="hiddenForm" hidden>

                <h3>Create Test</h3>

                @using (Html.BeginForm("Create", "Test", FormMethod.Post, new { @id = "target", @class = "form-horizontal", role = "form" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <input name="moduleId" type="text" value="@ViewBag.ModuleId" hidden />
                        <label>Test Name:</label>
                        <input name="name" type="text" class="form-control" placeholder="Test Name" style="margin-left: 17px;" required>
                    </div>

                    <button type="submit" class="btn btn-default">Create</button>
                }

            </div>
            break;
        case UserRole.Admin:
            break;
        default:
            throw new ArgumentOutOfRangeException();
    }
}

eUni.Client/eUni.Client/Views/Test/TakeTest.cshtml
@using Newtonsoft.Json
@model EUni_Client.Models.TestViewModel
    
<h2>@Model.Name</h2>


@foreach (var question in Model.Questions)
{
    <h3>@question.Text</h3>
    <label for="score_@question.QuestionId">Score:</label>
    <p id="score_@question.QuestionId">@question.Score</p>
    <div id="@question.QuestionId">
        @foreach (var answer in question.Answers)
        {
            <div>
                <input type="radio" name="[@question.QuestionId]answer" id="[@question.QuestionId]answer" value="@(JsonConvert.SerializeObject(answer))" />
                <label for="[@question.QuestionId]answer">@answer.Text</label>
            </div>
        }
    </div>
    <button type="button" class="btn btn-success" onclick="CheckAnswer(@question.QuestionId)" id="btn_@question.QuestionId">Submit Answer</button>
}

    <input hidden id="finalScore" name="finalScore"/>
    <a href="#myModal" data-toggle="modal" id="testBtn" class="btn btn-warning" onclick="SubmitTest(@ViewBag.StudentId, @ViewBag.TestId)">Submit Test</a>
    @*<a href="#myModal" class="btn btn-lg btn-primary" data-toggle="modal">Launch Demo Modal</a>*@

<div class="bs-example">
    <!-- Button HTML (to Trigger Modal) -->
    
    <!-- Modal HTML -->
    <div id="myModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">You're test is submited.</h4>
                </div>
                <div class="modal-body" id="updateDiv">
                    <p class="text-warning">Maximum grade: @ViewBag.TotalScore</p>
                </div>
                <div class="modal-footer">
                    @Html.ActionLink("Done", "Redirect", "Test", new RouteValueDictionary() { { "moduleId", Model.ModuleId}}, new Dictionary<string,object>{{"class", "btn btn-primary"} })
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-2.2.0.js"></script>
<script>
    var finalScore = 0;

    function CheckAnswer(id) {
        var data = $("#" + id + " div").children(":input:checked").val();
        var isCorrect = JSON.parse(data)["IsCorrect"];
        $("#" + id + " div").children(":input").prop("disabled", true);
        $("#btn_" + id).prop('disabled', true);

        var score = $("#score_" + id).text();

        if (isCorrect === true) {
            finalScore = +finalScore + +score;
        }
        $("#finalScore").val(finalScore);
        console.log(finalScore);
    };

    function SubmitTest(studentId, testId) {
        var grade = $("#finalScore").val();
        $("#testBtn").val("disabled", true);
        
        var newParagraph = document.createElement('p');
        newParagraph.textContent = "Your grade: " + finalScore;
        document.getElementById("updateDiv").appendChild(newParagraph);

        $.ajax({
            method: "POST",
            url: "/Test/SubmitFinalGrade",
            data: { studentId: studentId, finalScore: grade, testId: testId },
            success: function() {
                console.log("SUCCESS"); 
            }
        });
    };
</script>