eUni.Client/eUni.Client/Models/ModuleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EUni_Client.Models
{
    public class ModuleViewModel
    {
        public string Course { get; set; }
        public string  Name { get; set; }
        public string CourseCode { get; set; }
    }
}

eUni.Client/eUni.Client/Controllers/HomeworkController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using EUni_Client.Services;
using Newtonsoft.Json;

namespace EUni_Client.Controllers
{
    public class HomeworkController : Controller
    {
        // GET: Homework
        public async Task<ActionResult> Index(string hw, string module)
        {
            ViewBag.Homework = JsonConvert.DeserializeObject(hw);
            ViewBag.Module = JsonConvert.DeserializeObject(module);
            int homeworkId = ViewBag.Homework.HomeworkId;
            var apiService = Session.GetApiService();
            object homeworks = await apiService.GetAsync<IEnumerable<dynamic>, int>("/Homework/UploadedHomeworksByHomeworkId", "hwId", homeworkId);
            ViewBag.Homeworks = homeworks;
            return View();
        }

        [HttpPost]
        public async Task<RedirectToRouteResult> UploadHomework(HomweorkFileViewModel fileViewModel)
        {
            dynamic homework = JsonConvert.DeserializeObject(fileViewModel.Homework);
            var file = fileViewModel.Files[0];
            var bytes = file.InputStream.ToByteArray();
            var apiService = Session.GetApiService();
            var studentId = (await apiService.GetAsync<dynamic, string>("/User/GetByUsername", "username", apiService.Username)).DomainUserId;
            var result = await apiService.PostAsyncWithReturn<object, object>("/Homework/UploadHomeworkAnswer", new
            {
                StudentId = studentId,
                Filename = file.FileName,
                ContentFile = bytes,
                homeworkId = homework.HomeworkId
            });
            return RedirectToAction("Homework", "Module", new RouteValueDictionary { { "Module", fileViewModel.Module } });
        }

        [HttpPost]
        public async Task<RedirectToRouteResult> UpdateGrade(HomeworkGradeViewModel gradeViewModel)
        {
            var apiService = Session.GetApiService();
            var result = await apiService.PostAsyncWithReturn<object, object>("/Homework/AssignGradeToHomework", new
            {
                StudentId = gradeViewModel.StudId,
                HomeworkId = gradeViewModel.HomeworkId,
                Grade = gradeViewModel.Grade
            });
            return RedirectToAction("Index" ,"Homework", new RouteValueDictionary { {"hw", gradeViewModel.Homework}, { "module", gradeViewModel.Module} });
        }

        public class HomeworkGradeViewModel
        {
            public string StudId { get; set; }
            public string HomeworkId { get; set; }
            public string Homework { get; set; }
            public string Module { get; set; }
            public int Grade { get; set; }
        }
        public class HomweorkFileViewModel
        {
            public string Homework { get; set; }
            public string Module { get; set; }
            public HttpPostedFileBase[] Files { get; set; }
        }
    }
}

eUni.Client/eUni.Client/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using EUni_Client.Models;
using EUni_Client.Services;
using Newtonsoft.Json;

namespace EUni_Client.Controllers
{
    public class ModuleController : Controller
    {
        // GET: Module
        public ActionResult Index(string Module, string Course)
        {
            if (Course != null)
                ViewBag.Course = JsonConvert.DeserializeObject(Course);
            if (Module != null)
                ViewBag.Module = JsonConvert.DeserializeObject(Module);
            return View();
        }

        public async Task<ActionResult> Content(string Module, string Course)
        {
            var m = JsonConvert.DeserializeObject(Module);
            var ApiService = Session[ServiceNames.ApiService] as ApiService;
            var Files =
                await
                    ApiService.GetAsync<IEnumerable<dynamic>, int>("/File/DownloadLink", "moduleId",
                        (int) (((dynamic) m).ModuleId));
            ViewBag.Files = Files;
            //get all wikis
            var WikiPages =
                await
                    ApiService.GetAsync<IEnumerable<dynamic>, int>("/WikiPage/GetAllWikiPagesByModule", "moduleId",
                        (int) (((dynamic) m).ModuleId));
            ViewBag.WikiPages = WikiPages;
            //
            ViewBag.Module = JsonConvert.DeserializeObject(Module);
            if (Course != null)
                ViewBag.Course = JsonConvert.DeserializeObject(Course);
            return View();
        }

        public ActionResult UploadHomework()
        {
            return View();
        }


        public async Task<ActionResult> Homework(string Module, string Course)
        {
            dynamic module = ViewBag.Module = JsonConvert.DeserializeObject(Module);
            if (Course != null)
                ViewBag.Course = JsonConvert.DeserializeObject(Course);

            var apiService = Session.GetApiService();
            var moduleId = (int)module.ModuleId;
            var homeworks = await apiService.GetAsync<IEnumerable<object>, int>("/Homework/AllHomeworksByModuleId", "moduleId", moduleId);
            return View(homeworks);
        }
        public async Task<RedirectToRouteResult> CreateCourse(HomeworkCreateViewModel homework)
        {
            var apiService = Session.GetApiService();
            var result = await apiService.PostAsyncWithReturn<string, HomeworkCreateViewModel>("/Homework/Add", homework);
            //var data = new RouteValueDictionary();
            //data.Add("Module", course.Course);
            return RedirectToAction("Index", "Module");
        }
        public async Task<ActionResult> CreateHomework(string Module)
        {
            ViewBag.Module = JsonConvert.DeserializeObject(Module);
            return View();
        }

        public ActionResult CreateModule(string course)
        {
            var courseCode = ((dynamic)JsonConvert.DeserializeObject(course)).CourseCode;
            ViewBag.CourseCode = courseCode;
            ViewBag.Course = course;
            return View();
        }

        public async Task<RedirectToRouteResult> AddHomework(HomeworkCreateViewModel homeworkCreateViewModel)
        {
            var apiService = Session.GetApiService();
            var moduleId = ((dynamic)JsonConvert.DeserializeObject(homeworkCreateViewModel.Module)).ModuleId;
            var result = await apiService.PostAsyncWithReturn<object, object>("/Homework/Add", new
            {
                ModuleId = moduleId, homeworkCreateViewModel.Score, homeworkCreateViewModel.Text
            });
            return RedirectToAction("Index", "Module", new RouteValueDictionary() { {"Module", homeworkCreateViewModel.Module} });
        }



        [HttpPost]
        public async Task<ActionResult> Create(ModuleViewModel vm)
        {
            var apiService = Session.GetApiService();
            var result = await apiService.PostAsyncWithReturn<string, object>("/Module/Add", new {Name = vm.Name, CourseCode = vm.CourseCode});
            return RedirectToAction("Course", "Courses", new RouteValueDictionary() { {"c", vm.Course} });
        }


        public async Task<ActionResult> CreateResource(string Module)
        {
            var m = JsonConvert.DeserializeObject(Module);
            var apiService = Session.GetApiService();
            var files =
                await
                    apiService.GetAsync<IEnumerable<dynamic>, int>("/File/DownloadLink", "moduleId",
                        (int)(((dynamic)m).ModuleId));
            ViewBag.Files = files;
            ViewBag.Module = Module;
            return View();
        }


        [HttpPost]
        public async Task<RedirectToRouteResult> UploadModuleResource(FileViewModel fileViewModel)
        {
            dynamic module = JsonConvert.DeserializeObject(fileViewModel.Module);
            var file = fileViewModel.Files[0];
            var bytes = file.InputStream.ToByteArray();
            var apiService = Session.GetApiService();
            var result = await apiService.PostAsyncWithReturn<object, object>("/File/UploadFile", new
            {
                Filename = file.FileName,
                ContentFile = bytes,
                module.ModuleId
            });
            return RedirectToAction("CreateResource", "Module", new RouteValueDictionary { { "Module", fileViewModel.Module } });
        }


        public async Task<ActionResult> CreateQuestions(int moduleId)
        {
            var apiService = Session.GetApiService();
            var moduleQuestions = await apiService.GetAsync<IList<QuestionViewModel>, int>("/Question/GetAllByModuleId", "moduleId", moduleId);
            ViewBag.ModuleId = moduleId;

            return View(moduleQuestions);
        }

        [HttpPost]
        public async Task<ActionResult> AddQuestion(string text, int score, int moduleId, IList<string> answers, IList<string> isCorrect)
        {
            var apiService = Session.GetApiService();
            var questionId = await apiService.PostAsyncWithReturn<int, object>("/Question/Add", new { Text = text, Score = score, ModuleId = moduleId });

            var answersVm = new List<AnswerViewModel>();

            for (int i = 0; i < answers.Count(); i++)
            {
                answersVm.Add(new AnswerViewModel {QuestionId = questionId, Text = answers[i], IsCorrect = bool.Parse(isCorrect[i])});
            }

            await apiService.PostAsync("/Answer/CreateAnswersForQuestion", new { QuestionId = questionId, Answers = answersVm});

            return RedirectToAction("CreateQuestions", "Module", new RouteValueDictionary() { { "moduleId", moduleId } });
        }
    }

        public class FileViewModel
        {
            public string Module { get; set; }
            public HttpPostedFileBase[] Files { get; set; }
        }
        public class HomeworkCreateViewModel
        {
            public string Module { get; set; }
            public string Text { get; set; }
            public int Score { get; set; }
        }
    }

eUni.Client/eUni.Client/Controllers/WikiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using EUni_Client.Services;
using Newtonsoft.Json;

namespace EUni_Client.Controllers
{
    public class WikiController : Controller
    {
        // GET: Wiki
        public ActionResult Index(string Module, string Course)
        {
            if (Module != null)
                ViewBag.Module = JsonConvert.DeserializeObject(Module);
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public async Task<RedirectToRouteResult> CreateWiki(string wiki)
        {
            var wikiLocal = JsonConvert.DeserializeObject<WikiViewModel>(wiki);
            var apiService = Session.GetApiService();
            var result = await apiService.PostAsyncWithReturn<string, WikiViewModel>("/WikiPage/Add", wikiLocal);
            var data = new RouteValueDictionary {{"Module", wikiLocal.Module}};
            return RedirectToAction("Index", "Module", data);
        }

        public class WikiViewModel
        {
            public int ModuleId { get; set; }
            public string Content { get; set; }
            public string Module { get; set; }
        }
    }
}

eUni.Client/eUni.Client/Views/Module/Content.cshtml
<h3>@ViewBag.Module.Name Content</h3>
<br>


@{
    var i = 0;
    <h5>Resources</h5>
    if (ViewBag.Files.Count > 0)
    {
        <table class="table table-striped table-hover">
            <tr>
                <th>#</th>
                <th>File Name</th>
                <th>Path</th>
            </tr>
            @foreach (var file in ViewBag.Files)
            {
            i++;
            <tr>
                <td>@i</td>
                <td>
                    @file.Filename
                </td>
                <td>
                    <a href="@file.Path" class="btn btn-primary" style="width: 150px">
                        <div class="glyphicon glyphicon-download col-md-1" style="margin: 5px 0 0 0">
                        </div>
                        <div style="font-family: Roboto; margin: 1px 0 0 0">Download</div>
                    </a>
                </td>
            </tr>
            }
        </table>

    }
    else
    {
        <h5>No content to show!</h5>
    }
}
<br>
<br>

    @{
        <h5>Content</h5>
        foreach (var page in ViewBag.WikiPages)
        {
            <li>@Html.Raw(page.Content)</li>
        }
    }

eUni.Client/eUni.Client/Views/Module/CreateHomework.cshtml
<h3>Create Homework</h3>
@using (Html.BeginForm("AddHomework", "Module", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @id = "target", @class = "form-horizontal", role = "form" }))
{
    <input name="Module" value="@ViewBag.Module" style="display: none" />
    <label>Homework Text:</label>
        <textarea name="Text" rows="10" cols="500"></textarea>
        <br>
        <label>Homework Score:</label>
        <input name="Score" type='text' class="form-control" id='sandbox-container2' placeholder="Ending" required />
        <button type="submit" class="btn btn-default">Create</button>
}

eUni.Client/eUni.Client/Views/Module/CreateModule.cshtml
<h2>Create Module</h2>

@using (Html.BeginForm("Create", "Module", FormMethod.Post, new { @id = "target", @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <input name="Course" value="@ViewBag.Course" hidden/>
    <div class="form-group">
        <label>Module Name</label>
        <input name="name" type="text" class="form-control" placeholder="Module Name" style="margin-left: 17px;" required>
    </div>
    <div class="form-group">
        <label>Course Code</label>
        <input name="CourseCode" type="text" class="form-control" value="@ViewBag.CourseCode" style="margin-left: 17px;" readonly="readonly">
    </div>
    
    <button type="submit" class="btn btn-default">Create</button>
}

eUni.Client/eUni.Client/Views/Module/CreateQuestions.cshtml
@model IList<EUni_Client.Models.QuestionViewModel>

<br/><br/>

<title>Create Questions</title>


@if (Model == null || Model.Count == 0)
{
    <p>No questions for this module. Feel free to add.</p>
}
else
{
    <table class="table table-striped table-hover">
        <tr>
            <th>#Id</th>
            <th>Text</th>
            <th>Score</th>
        </tr>
        @foreach (var question in Model)
        {
            <tr>
                <td>@question.QuestionId</td>
                <td>@question.Text</td>
                <td>@question.Score</td>
            </tr>
        }
    </table>
}

    @using (Ajax.BeginForm("AddQuestion", "Module", new AjaxOptions { HttpMethod = "POST"}, new {id="myForm"}))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <label>Question:</label>
            <input class="form-control" name="text" required=""/>
        </div>
        <div class="form-group">
            <label>Score:</label>
            <input type="number" class="form-control" name="score" required/>
        </div>
        <input name="moduleId" value="@ViewBag.ModuleId" hidden/>

        <label>Answers:</label>
        <div class="multi-field-wrapper">
            <div class="multi-fields">
                <div class="multi-field form-group">
                    <input type="text" name="answers" required>
                    <input type="checkbox" name="isCorrect" onclick="toggle(this)" value="false"/>
                    <button type="button" class="remove-field btn btn-danger">Remove</button>
                    <br/>
                </div>
            </div>
            <button type="button" class="add-field">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            </button>
        </div>
        <br/>

        <button type="submit" class="btn btn-default" id="submitBtn">Submit</button>
    }

<script src="~/Scripts/jquery-2.2.0.js"></script>
<script>
    $("#myForm").submit(function (event) {
        var temp = $('input:checkbox');
        temp.each(function () {
            $(this).prop('checked', true);
        });
        $("#submitBtn").prop("disabled", true);
    });
    

    $('.multi-field-wrapper').each(function () {
        var $wrapper = $('.multi-fields', this);
        $(".add-field", $(this)).click(function (e) {
            $('.multi-field:first-child', $wrapper).clone(true).appendTo($wrapper).find('input').val('').focus();
        });
        $('.multi-field .remove-field', $wrapper).click(function () {
            if ($('.multi-field', $wrapper).length > 1)
                $(this).parent('.multi-field').remove();
        });
    });

    function toggle(button) {
        var temp = $('input:checkbox');
        temp.each(function() {
            $(this).val(false);
            $(this).prop('checked', false);
        });

        $(button).val(true);
        $(button).prop('checked', true);
    }
</script>

eUni.Client/eUni.Client/Views/Module/CreateResource.cshtml
<h2>Create Module Resource</h2>

<table class="table table-striped table-hover">
    <tr>
        <th>#</th>
        <th>File Name</th>
        <th>Path</th>
    </tr>
    @{
        var i = 0;
        foreach (var file in ViewBag.Files)
        {
            i++;
            <tr>
                <td>@i</td>
                <td>
                    <a href="@file.Path">@file.Filename</a>
                </td>
                <td>@file.Path</td>
            </tr>
        }
    }
</table>

@using (Html.BeginForm("UploadModuleResource", "Module", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        <div class="">
            <input type="text" name="Module" value="@ViewBag.Module" style="display: none" />
            <input type="file" id="Avatar" name="Files" class="btn" />
            <br />
            <input type="submit" value="Upload Resource" class="btn btn-default" />
        </div>
    </div>
}

eUni.Client/eUni.Client/Views/Module/Homework.cshtml
@using EUni_Client.Services

<h3>@ViewBag.Module.Name Homework</h3>
<br>

@Scripts.Render("~/bundles/jquery")

@if (Model.Count > 0)
{
    <table class="table table-striped table-hover">
        <tr>
            <th>#</th>
            <th>Homework</th>
            <th>Score</th>
        </tr>
        @{
            var i = 0;
            foreach (var homework in Model)
            {
                i++;
                <tr>
                    <td>@i</td>
                    <td>
                        @using (Html.BeginForm("Index", "Homework"))
                        {
                            <input name="hw" value="@homework" hidden/>
                            <input name="module" value="@ViewBag.Module" hidden/>
                            <input type="submit" class="btn-link" style="color: dodgerblue" value="@homework.Text">
                        }
                    </td>
                    <td>@homework.Score</td>
                </tr>
            }
        }
    </table>
}
else
{
    <h5>No homework to show!</h5>
}

@if (Session[ServiceNames.ApiService] != null)
{
    var role = Session.GetApiService().UserRole;
    switch (role)
    {
        case UserRole.Student:
            break;
        case UserRole.Teacher:
            using (Html.BeginForm("CreateHomework", "Module"))
            {
                <input name="Module" value="@ViewBag.Module" style="display: none" />
                <input type="submit" class="btn btn-default" value="Create Homework" />
            }
            break;
        case UserRole.Admin:
            break;
        default:
            throw new ArgumentOutOfRangeException();
    }
}

eUni.Client/eUni.Client/Views/Module/Index.cshtml
@using EUni_Client.Services


@if (ViewBag.module != null)
{<h3>@ViewBag.Module.Name</h3>}


@using (Html.BeginForm("Content", "Module"))
{
    <input name="Module" value="@ViewBag.Module" style="display: none" />
    <input name="Course" value="@ViewBag.Course" style="display: none" />
    <input type="submit" class="btn-link" style="color: dodgerblue" value="Content" />
}

@if (Session[ServiceNames.ApiService] != null)
{
    var role = Session.GetApiService().UserRole;
    switch (role)
    {
        case UserRole.Student:
            using (Html.BeginForm("Index", "Test"))
            {
                <input name="moduleId" value="@ViewBag.Module.ModuleId" style="display: none" />
                <input name="Module" value="@ViewBag.Module" style="display: none" />
                <input name="Course" value="@ViewBag.Course" style="display: none" />
                <input type="submit" class="btn-link" style="color: dodgerblue" value="Test" />
            }
            using (Html.BeginForm("Homework", "Module"))
            {
                <input name="Module" value="@ViewBag.Module" style="display: none" />
                <input name="Course" value="@ViewBag.Course" style="display: none" />
                <input type="submit" class="btn-link" style="color: dodgerblue" value="Homework" />
            }
            break;
        case UserRole.Teacher:
            using (Html.BeginForm("Index", "Wiki"))
            {
                <input name="Module" value="@ViewBag.Module" style="display: none" />
                <input name="Course" value="@ViewBag.Course" style="display: none" />
                <input type="submit" class="btn-link" style="color: dodgerblue" value="Wiki" />
            }
            using (Html.BeginForm("CreateResource", "Module"))
            {
                <input name="Module" value="@ViewBag.Module" style="display: none" />
                <input type="submit" class="btn-link" style="color: dodgerblue" value="Resources" />
            }
            using (Html.BeginForm("Index", "Test"))
            {
                <input name="moduleId" value="@ViewBag.Module.ModuleId" style="display: none" />
                <input name="Module" value="@ViewBag.Module" style="display: none" />
                <input name="Course" value="@ViewBag.Course" style="display: none" />
                <input type="submit" class="btn-link" style="color: dodgerblue" value="Test" />
            }
            using (Html.BeginForm("Homework", "Module"))
            {
                <input name="Module" value="@ViewBag.Module" style="display: none" />
                <input name="Course" value="@ViewBag.Course" style="display: none" />
                <input type="submit" class="btn-link" style="color: dodgerblue" value="Homework" />
            }
            break;
        case UserRole.Admin:
            break;
        default:
            throw new ArgumentOutOfRangeException();
    }
}

<br>

@if (Session[ServiceNames.ApiService] != null)
{
    var role = Session.GetApiService().UserRole;
    switch (role)
    {
        case UserRole.Student:
            break;
        case UserRole.Teacher:
            using (Html.BeginForm("CreateQuestions", "Module"))
            {
                <input name="moduleId" value="@ViewBag.Module.ModuleId" style="display: none" />
                <input type="submit" class="btn btn-default" value="Create Questions for Module" />
            }
            <br/>
            using (Html.BeginForm("CreateModule", "Module"))
            {
                <input name="Course" value="@ViewBag.Course" style="display: none" />
                <input class="btn btn-default" type="submit" value="Create Module" />
            }

            break;
        case UserRole.Admin:
            break;
        default:
            throw new ArgumentOutOfRangeException();
    }
}


@*@Html.ActionLink("Create homework", "CreateHomework", "Module", new
{
    Module = ViewBag.Module,
    Course = ViewBag.Course
        
}, new { @class = "btn btn-default" })*@

eUni.Client/eUni.Client/Views/Module/UploadHomework.cshtml
<h2>title</h2>